# Generated by Django 6.0.7 on 2026-07-28 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_recentlyviewedproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='store_products/gallery/%Y-%m-%d')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Product Gallery Images',
                'ordering': ['id'],
            },
        ),
    ]
