# Generated by Django 6.0.7 on 2026-07-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_wishlist_unique_together_wishlist_session_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='8471', max_length=20, verbose_name='HSN/SAC Code'),
        ),
    ]
