# Generated by Django 6.0.7 on 2026-07-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('icon', models.CharField(default='laptop', help_text='Lucide icon name (e.g. laptop, printer, video, Wrench)', max_length=50)),
                ('icon_bg_color', models.CharField(default='bg-blue-50 text-[var(--color-primary)]', help_text='Tailwind background & text color classes', max_length=100)),
                ('short_description', models.TextField()),
                ('bullet_points', models.JSONField(blank=True, default=list, help_text="JSON array of bullet points e.g. ['Point 1', 'Point 2']")),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('service_category', models.CharField(max_length=100)),
                ('preferred_time', models.CharField(choices=[('Morning (9:00 AM – 12:00 PM)', 'Morning (9:00 AM – 12:00 PM)'), ('Afternoon (12:00 PM – 3:00 PM)', 'Afternoon (12:00 PM – 3:00 PM)'), ('Evening (3:00 PM – 6:00 PM)', 'Evening (3:00 PM – 6:00 PM)')], default='Morning (9:00 AM – 12:00 PM)', max_length=100)),
                ('issue_description', models.TextField()),
                ('device_photo', models.ImageField(blank=True, null=True, upload_to='service_requests/%Y-%m-%d')),
                ('status', models.CharField(choices=[('pending', 'Pending / New'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes for technicians')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Service Requests / Booking Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
