# Generated by Django 6.0.7 on 2026-07-28 08:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitem_options_cartitem_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Flat shipping charge (₹). Set 0 for free shipping by default.', max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Orders above this subtotal get free shipping. Set 0 to disable threshold-based free shipping.', max_digits=12)),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, shipping is always FREE.')),
            ],
            options={
                'verbose_name': 'Shipping Configuration',
                'verbose_name_plural': 'Shipping Configuration',
            },
        ),
    ]
