# Generated by Django 6.0.7 on 2026-07-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_orderitem_useraddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name_plural': 'User Addresses'},
        ),
    ]
