# Generated by Django 6.0.7 on 2026-08-01 03:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_useraddress_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
