# Generated by Django 6.0.7 on 2026-08-01 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_order_invoice_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice_access_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
