# Generated by Django 6.0.7 on 2026-07-28 07:44

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique coupon code (stored & matched in uppercase).', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text='Short description shown to admin (e.g. "Welcome offer ₹500 off").', max_length=255)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed Amount (₹)'), ('percentage', 'Percentage (%)')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount value — flat ₹ amount or percentage.', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart subtotal required to use this coupon.', max_digits=12)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on max discount for percentage coupons (leave blank for no cap).', max_digits=12, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Max number of times this coupon can be used (blank = unlimited).', null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, help_text='Coupon expiry date/time (blank = never expires).', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
    ]
